[build]
  functions = "functions" # directory for serverless functions
  # Remove the publish line if you don't have a public directory
  # publish = "public"     

[[redirects]]
  from = "/*"
  to = "/index.html" # Make sure to have an index.html in the public folder if you keep this line
  status = 200
